name: base
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  # - biobb_analysis==4.2.0
  # - biobb_io==4.2.0
  # - biobb_structure_utils==4.2.0
  # - biobb_chemistry==4.2.0
  - biobb_amber==4.2.0
  # - jupyter  # takes off 600MB
  - gfortran==11.3.0
  - libgfortran5==11.3.0
  # install in separate image once done checking
  - plotly
  # - nglview
  # - simpletraj
  - pip
  - pip:
    - kfp
    - kfp-kubernetes
