[project]
name = "kubeflow-setup"
version = "1.0.0"
description = "Setup for an AMBER notebook -> Kubeflow pipeline."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "biobb-amber>=5.0.4",
    "kfp-kubernetes>=1.4.0",
    "kfp>=2.11.0",
]
